#pragma once

#define SHARON_MOUSE_BUTTON_1         0
#define SHARON_MOUSE_BUTTON_2         1
#define SHARON_MOUSE_BUTTON_3         2
#define SHARON_MOUSE_BUTTON_4         3
#define SHARON_MOUSE_BUTTON_5         4
#define SHARON_MOUSE_BUTTON_6         5
#define SHARON_MOUSE_BUTTON_7         6
#define SHARON_MOUSE_BUTTON_8         7
#define SHARON_MOUSE_BUTTON_LAST      SHARON_MOUSE_BUTTON_8
#define SHARON_MOUSE_BUTTON_LEFT      SHARON_MOUSE_BUTTON_1
#define SHARON_MOUSE_BUTTON_RIGHT     SHARON_MOUSE_BUTTON_2
#define SHARON_MOUSE_BUTTON_MIDDLE    SHARON_MOUSE_BUTTON_3